# cask_args appdir: "/Applications/HomeBrew", require_sha: true
cask_args require_sha: true

# repo = "a7ex/homebrew-formulae"
# tap repo, "https://github.com/#{repo}.git"
tap "oclint/formulae"
tap "getsentry/tools"
# tap "homebrew/cask-versions"
# tap "homebrew/core"
# tap "homebrew/cask"
#tap "homebrew/bundle"

brew "mas"
brew "whalebrew"
brew "circleci"
brew "cmake"
brew "cocoapods"
brew "duti"
brew "fastlane"
brew "harfbuzz"
brew "gh"
brew "gnupg"
brew "llvm"
brew "markdown"
brew "openjdk@17"
brew "pinentry-mac"
brew "shadowsocks-rust"
brew "shc"
brew "shellcheck"
brew "swiftlint"
brew "vapoursynth"
brew "hub"
brew "rbenv"
brew "ruby-build"
brew "gpg2"
brew "chruby"
brew "ruby-install"
brew "rustup"
brew "swift-sh"
brew "node"
brew "watchman"
brew "yarn"
brew "blueutil"
brew "xcresultparser"
brew "xclogparser"
brew "kdoctor"
brew "libimobiledevice"
brew "jq"
brew "automake"
brew "bison"
brew "libyaml"
brew "openssl"
brew "gdbm"
brew "readline"
brew "libffi"
brew "wget"
brew "oclint"
brew "mint"
brew "scrcpy"
brew "getsentry/tools/sentry-wizard"
brew "getsentry/tools/sentry-cli"
brew "mise"
brew "xcodegen"
brew "codex"
# brew "nss"
# brew "rustup-init"
# brew "netbirdio/tap/netbird"
# brew "openssl@1.1"
# brew "youtube-dl"
# brew "txt2tags"
# brew "pandoc"
# brew "multimarkdown"
# brew "texi2html"

cask "1password"
cask "1password-cli"
cask "firefox"
cask "fork"
cask "google-drive", args: { "require_sha": false }
cask "stolendata-mpv"
cask "netnewswire"
cask "proxyman"
cask "qbittorrent"
cask "warp"
cask "zoom"
cask "db-browser-for-sqlite"
cask "android-file-transfer"
cask "monitorcontrol"
cask "expressvpn"
cask "xcodes-app"
cask "android-platform-tools"
cask "ungoogled-chromium"
cask "cursor"
cask "obsidian"
cask "grammarly-desktop"
cask "simsim"
cask "chatgpt", args: { "no-quarantine": true }
cask "cloudflare-warp"
cask "thunderbird"
#cask "firefox@nightly", args: { "require_sha": false }
#cask "blackhole-2ch"
#cask "discord" 
# cask "windsurf"
# cask "github"
# cask "streamlabs"
# cask "sourcetree"
# cask "bluebubbles"
# cask "claude"
# cask "xnapper"
# cask "google-chrome", args: { "require_sha": false }
# cask "eqmac"
# cask "unified-remote"
# cask "librewolf", args: { "no-quarantine": true }
# cask "visual-studio-code"
# cask "github-copilot-for-xcode"
# cask "charles"
# cask "multiviewer-for-f1"
# cask "copilot-for-xcode"
# cask "slack"
# cask "proxy-audio-device"
# cask "gpg-suite"
# cask "veracrypt"
# cask "notion"
# cask "ticktick"
# cask "gitkraken"
# cask "telegram"
# cask "audio-hijack", args: { "require_sha": false }
# cask "bluestacks"
# cask "joplin"
# cask "bluesnooze"
# cask "buildsettingextractor"
# cask "macfuse"
# cask "arc"
# cask "bettertouchtool"
# cask "krisp"
# cask "obs"
# cask "nordvpn"
# cask "intellij-idea-ce"
# cask "docker"
# cask "postman"
# cask "vmware-fusion"
# cask "netbirdio/tap/netbird-ui"
# cask "spotify"
# cask "firefox-developer-edition", args: { "require_sha": false }
# cask "fig"
# cask "betterdisplay"
# cask "audacity"
# cask "intellij-idea"
# cask "android-studio"
# cask "protonvpn"
# cask "nordvpn"
# cask "pocket-casts"\
# cask "vlc"
# cask "raycast"
# cask "virtualbox"
# cask "whatsapp"
# cask "macs-fan-control"
# cask "microsoft-teams"
# cask "clion"
# cask "doxygen"
# cask "discord-canary"

# mas "DevCleaner", id: 1388020431
# mas "Amphetamine", id: 937984704
# mas "Shazam", id: 897118787
# mas "The Unarchiver", id: 425424353
# mas "CleanMyMac", id: 1339170533
# mas "MuteKey", id: 1509590766

# mas "Xcode", id: 497799835
# mas "Developer", id: 640199958
# mas "Microsoft Excel", id: 462058435
# mas "Microsoft PowerPoint", id: 462062816
# mas "Microsoft Word", id: 462054704
# mas "RocketSim", id: 1504940162
# mas "GarageBand", id: 682658836
# mas "iMovie", id: 408981434
# mas "Testflight", id: 899247664
# mas "Betternet", id: 1028905953
# mas "Pocket", id: 568494494
# mas "Twitter", id: 1482454543
# mas "Massenger", id: 1480068668
